export const items = [
  "Blackboard",
  "Computers",
  "Projector",
  "White Board",
  "Scanner",
  "Printer",
  "Furniture",
];

export const currentInventory = [
  {
    id: 0,
    item: "Blackboard",
    category: "Class Material",
    quantity: 56,
  },
  {
    id: 1,
    item: "Computers",
    category: "Equipments",
    quantity: 210,
  },
  {
    id: 2,
    item: "Projector",
    category: "Equipments",
    quantity: 20,
  },
  {
    id: 3,
    item: "White Board",
    category: "Class Material",
    quantity: 46,
  },
];

export const blackboardDetails = [
  {
    productId: "BB-001",
    itemName: "Blackboard",
    brand: "ABC Educational Supplies",
    purchaseDate: "2024-01-15",
    location: "Room 101",
    invoiceLink: "#",
  },
  {
    productId: "BB-002",
    itemName: "Blackboard",
    brand: "XYZ Learning Co.",
    purchaseDate: "2022-02-10",
    location: "Room 102",
    invoiceLink: "#",
  },
  {
    productId: "BB-003",
    itemName: "Blackboard",
    brand: "Classroom Essentials",
    purchaseDate: "2024-02-20",
    location: "Room 103",
    invoiceLink: "#",
  },
  {
    productId: "BB-004",
    itemName: "Blackboard",
    brand: "TeachTools Inc.",
    purchaseDate: "2022-03-01",
    location: "Room 104",
    invoiceLink: "#",
  },
  {
    productId: "BB-005",
    itemName: "Blackboard",
    brand: "EduMatters",
    purchaseDate: "2022-03-10",
    location: "Room 105",
    invoiceLink: "#",
  },
  {
    productId: "BB-006",
    itemName: "Blackboard",
    brand: "LearnPro Supplies",
    purchaseDate: "2024-03-15",
    location: "Room 106",
    invoiceLink: "#",
  },
  {
    productId: "BB-007",
    itemName: "Blackboard",
    brand: "Classroom Essentials",
    purchaseDate: "2024-03-20",
    location: "Room 107",
    invoiceLink: "#",
  },
  {
    productId: "BB-008",
    itemName: "Blackboard",
    brand: "ABC Educational Supplies",
    purchaseDate: "2022-04-01",
    location: "Room 108",
    invoiceLink: "#",
  },
  {
    productId: "BB-009",
    itemName: "Blackboard",
    brand: "XYZ Learning Co.",
    purchaseDate: "2024-04-10",
    location: "Room 109",
    invoiceLink: "#",
  },
  {
    productId: "BB-010",
    itemName: "Blackboard",
    brand: "TeachTools Inc.",
    purchaseDate: "2022-04-15",
    location: "Room 110",
    invoiceLink: "#",
  },
  {
    productId: "BB-011",
    itemName: "Blackboard",
    brand: "EduMatters",
    purchaseDate: "2022-04-20",
    location: "Room 111",
    invoiceLink: "#",
  },
];

export const computerDetails = [
  {
    productId: "PC-001",
    itemName: "Desktop Computer",
    brand: "Dell",
    purchaseDate: "2024-01-10",
    location: "Computer Lab 1",
    invoiceLink: "#",
  },
  {
    productId: "PC-002",
    itemName: "Laptop",
    brand: "HP",
    purchaseDate: "2024-01-15",
    location: "Room 201",
    invoiceLink: "#",
  },
  {
    productId: "PC-003",
    itemName: "Desktop Computer",
    brand: "Lenovo",
    purchaseDate: "2025-01-20",
    location: "Computer Lab 2",
    invoiceLink: "#",
  },
  {
    productId: "PC-004",
    itemName: "Laptop",
    brand: "Apple",
    purchaseDate: "2025-01-25",
    location: "Room 202",
    invoiceLink: "#",
  },
  {
    productId: "PC-005",
    itemName: "Desktop Computer",
    brand: "Acer",
    purchaseDate: "2024-01-30",
    location: "Computer Lab 1",
    invoiceLink: "#",
  },
  {
    productId: "PC-006",
    itemName: "Laptop",
    brand: "Asus",
    purchaseDate: "2024-02-05",
    location: "Room 203",
    invoiceLink: "#",
  },
  {
    productId: "PC-007",
    itemName: "Desktop Computer",
    brand: "HP",
    purchaseDate: "2025-02-10",
    location: "Computer Lab 3",
    invoiceLink: "#",
  },
  {
    productId: "PC-008",
    itemName: "Laptop",
    brand: "Dell",
    purchaseDate: "2025-02-15",
    location: "Room 204",
    invoiceLink: "#",
  },
  {
    productId: "PC-009",
    itemName: "Desktop Computer",
    brand: "Apple",
    purchaseDate: "2025-02-20",
    location: "Computer Lab 2",
    invoiceLink: "#",
  },
  {
    productId: "PC-010",
    itemName: "Laptop",
    brand: "Lenovo",
    purchaseDate: "2024-02-25",
    location: "Room 205",
    invoiceLink: "#",
  },
  {
    productId: "PC-011",
    itemName: "Desktop Computer",
    brand: "Asus",
    purchaseDate: "2024-03-01",
    location: "Computer Lab 3",
    invoiceLink: "#",
  },
  {
    productId: "PC-012",
    itemName: "Laptop",
    brand: "Acer",
    purchaseDate: "2024-03-05",
    location: "Room 206",
    invoiceLink: "#",
  },
  {
    productId: "PC-013",
    itemName: "Desktop Computer",
    brand: "Dell",
    purchaseDate: "2024-03-10",
    location: "Computer Lab 1",
    invoiceLink: "#",
  },
  {
    productId: "PC-014",
    itemName: "Laptop",
    brand: "HP",
    purchaseDate: "2024-03-15",
    location: "Room 207",
    invoiceLink: "#",
  },
  {
    productId: "PC-015",
    itemName: "Desktop Computer",
    brand: "Lenovo",
    purchaseDate: "2024-03-20",
    location: "Computer Lab 2",
    invoiceLink: "#",
  },
  {
    productId: "PC-016",
    itemName: "Laptop",
    brand: "Apple",
    purchaseDate: "2024-03-25",
    location: "Room 208",
    invoiceLink: "#",
  },
  {
    productId: "PC-017",
    itemName: "Desktop Computer",
    brand: "Acer",
    purchaseDate: "2024-03-30",
    location: "Computer Lab 3",
    invoiceLink: "#",
  },
  {
    productId: "PC-018",
    itemName: "Laptop",
    brand: "Asus",
    purchaseDate: "2024-04-05",
    location: "Room 209",
    invoiceLink: "#",
  },
  {
    productId: "PC-019",
    itemName: "Desktop Computer",
    brand: "HP",
    purchaseDate: "2024-04-10",
    location: "Computer Lab 1",
    invoiceLink: "#",
  },
  {
    productId: "PC-020",
    itemName: "Laptop",
    brand: "Dell",
    purchaseDate: "2024-04-15",
    location: "Room 210",
    invoiceLink: "#",
  },
];

export const projectorDetails = [
  {
    productId: "PJ-001",
    itemName: "Projector",
    brand: "Epson",
    purchaseDate: "2024-02-01",
    location: "Room 101",
    invoiceLink: "#",
  },
  {
    productId: "PJ-002",
    itemName: "Projector",
    brand: "BenQ",
    purchaseDate: "2024-02-05",
    location: "Room 102",
    invoiceLink: "#",
  },
  {
    productId: "PJ-003",
    itemName: "Projector",
    brand: "Sony",
    purchaseDate: "2024-02-10",
    location: "Room 103",
    invoiceLink: "#",
  },
  {
    productId: "PJ-004",
    itemName: "Projector",
    brand: "Optoma",
    purchaseDate: "2024-02-15",
    location: "Room 104",
    invoiceLink: "#",
  },
  {
    productId: "PJ-005",
    itemName: "Projector",
    brand: "LG",
    purchaseDate: "2024-02-20",
    location: "Room 105",
    invoiceLink: "#",
  },
  {
    productId: "PJ-006",
    itemName: "Projector",
    brand: "ViewSonic",
    purchaseDate: "2024-02-25",
    location: "Room 106",
    invoiceLink: "#",
  },
  {
    productId: "PJ-007",
    itemName: "Projector",
    brand: "Panasonic",
    purchaseDate: "2024-03-01",
    location: "Room 107",
    invoiceLink: "#",
  },
  {
    productId: "PJ-008",
    itemName: "Projector",
    brand: "Acer",
    purchaseDate: "2024-03-05",
    location: "Room 108",
    invoiceLink: "#",
  },
  {
    productId: "PJ-009",
    itemName: "Projector",
    brand: "Casio",
    purchaseDate: "2024-03-10",
    location: "Room 109",
    invoiceLink: "#",
  },
  {
    productId: "PJ-010",
    itemName: "Projector",
    brand: "Hitachi",
    purchaseDate: "2024-03-15",
    location: "Room 110",
    invoiceLink: "#",
  },
];

export const whiteboardDetails = [
  {
    productId: "WB-001",
    itemName: "Whiteboard",
    brand: "Quartet",
    purchaseDate: "2024-01-10",
    location: "Room 201",
    invoiceLink: "#",
  },
  {
    productId: "WB-002",
    itemName: "Whiteboard",
    brand: "EXPO",
    purchaseDate: "2024-01-15",
    location: "Room 202",
    invoiceLink: "#",
  },
  {
    productId: "WB-003",
    itemName: "Whiteboard",
    brand: "VIZ-PRO",
    purchaseDate: "2024-01-20",
    location: "Room 203",
    invoiceLink: "#",
  },
  {
    productId: "WB-004",
    itemName: "Whiteboard",
    brand: "U Brands",
    purchaseDate: "2024-01-25",
    location: "Room 204",
    invoiceLink: "#",
  },
  {
    productId: "WB-005",
    itemName: "Whiteboard",
    brand: "Office Depot",
    purchaseDate: "2024-01-30",
    location: "Room 205",
    invoiceLink: "#",
  },
  {
    productId: "WB-006",
    itemName: "Whiteboard",
    brand: "AmazonBasics",
    purchaseDate: "2024-02-05",
    location: "Room 206",
    invoiceLink: "#",
  },
  {
    productId: "WB-007",
    itemName: "Whiteboard",
    brand: "Luxor",
    purchaseDate: "2024-02-10",
    location: "Room 207",
    invoiceLink: "#",
  },
];

export const scannerDetails = [
  {
    productId: "SC-001",
    itemName: "Scanner",
    brand: "Canon",
    purchaseDate: "2024-02-01",
    location: "Office 101",
    invoiceLink: "#",
  },
  {
    productId: "SC-002",
    itemName: "Scanner",
    brand: "Epson",
    purchaseDate: "2024-02-05",
    location: "Office 102",
    invoiceLink: "#",
  },
  {
    productId: "SC-003",
    itemName: "Scanner",
    brand: "HP",
    purchaseDate: "2024-02-10",
    location: "Office 103",
    invoiceLink: "#",
  },
  {
    productId: "SC-004",
    itemName: "Scanner",
    brand: "Brother",
    purchaseDate: "2024-02-15",
    location: "Office 104",
    invoiceLink: "#",
  },
  {
    productId: "SC-005",
    itemName: "Scanner",
    brand: "Fujitsu",
    purchaseDate: "2024-02-20",
    location: "Office 105",
    invoiceLink: "#",
  },
];

export const printerDetails = [
  {
    productId: "PR-001",
    itemName: "Printer",
    brand: "HP",
    purchaseDate: "2024-03-01",
    location: "Print Room 1",
    invoiceLink: "#",
  },
  {
    productId: "PR-002",
    itemName: "Printer",
    brand: "Canon",
    purchaseDate: "2024-03-05",
    location: "Print Room 2",
    invoiceLink: "#",
  },
  {
    productId: "PR-003",
    itemName: "Printer",
    brand: "Epson",
    purchaseDate: "2024-03-10",
    location: "Print Room 3",
    invoiceLink: "#",
  },
  {
    productId: "PR-004",
    itemName: "Printer",
    brand: "Brother",
    purchaseDate: "2024-03-15",
    location: "Print Room 4",
    invoiceLink: "#",
  },
  {
    productId: "PR-005",
    itemName: "Printer",
    brand: "Lexmark",
    purchaseDate: "2024-03-20",
    location: "Print Room 5",
    invoiceLink: "#",
  },
];

export const furnitureDetails = [
  {
    productId: "FR-001",
    itemName: "Table",
    brand: "IKEA",
    purchaseDate: "2024-03-01",
    location: "Room 301",
    invoiceLink: "#",
  },
  {
    productId: "FR-002",
    itemName: "Chair",
    brand: "Office Depot",
    purchaseDate: "2024-03-05",
    location: "Room 302",
    invoiceLink: "#",
  },
  {
    productId: "FR-003",
    itemName: "Fan",
    brand: "Honeywell",
    purchaseDate: "2024-03-10",
    location: "Room 303",
    invoiceLink: "#",
  },
  {
    productId: "FR-004",
    itemName: "Light",
    brand: "Philips",
    purchaseDate: "2024-03-15",
    location: "Room 304",
    invoiceLink: "#",
  },
  {
    productId: "FR-005",
    itemName: "Table",
    brand: "Wayfair",
    purchaseDate: "2024-03-20",
    location: "Room 305",
    invoiceLink: "#",
  },
  {
    productId: "FR-006",
    itemName: "Chair",
    brand: "Herman Miller",
    purchaseDate: "2024-03-25",
    location: "Room 306",
    invoiceLink: "#",
  },
  {
    productId: "FR-007",
    itemName: "Fan",
    brand: "Dyson",
    purchaseDate: "2024-04-01",
    location: "Room 307",
    invoiceLink: "#",
  },
  {
    productId: "FR-008",
    itemName: "Light",
    brand: "GE",
    purchaseDate: "2024-04-05",
    location: "Room 308",
    invoiceLink: "#",
  },
  {
    productId: "FR-009",
    itemName: "Table",
    brand: "West Elm",
    purchaseDate: "2024-04-10",
    location: "Room 309",
    invoiceLink: "#",
  },
  {
    productId: "FR-010",
    itemName: "Chair",
    brand: "Steelcase",
    purchaseDate: "2024-04-15",
    location: "Room 310",
    invoiceLink: "#",
  },
  {
    productId: "FR-011",
    itemName: "Fan",
    brand: "Lasko",
    purchaseDate: "2024-04-20",
    location: "Room 311",
    invoiceLink: "#",
  },
  {
    productId: "FR-012",
    itemName: "Light",
    brand: "Osram",
    purchaseDate: "2024-04-25",
    location: "Room 312",
    invoiceLink: "#",
  },
  {
    productId: "FR-013",
    itemName: "Table",
    brand: "CB2",
    purchaseDate: "2024-05-01",
    location: "Room 313",
    invoiceLink: "#",
  },
  {
    productId: "FR-014",
    itemName: "Chair",
    brand: "Eames",
    purchaseDate: "2024-05-05",
    location: "Room 314",
    invoiceLink: "#",
  },
  {
    productId: "FR-015",
    itemName: "Fan",
    brand: "Bionaire",
    purchaseDate: "2024-05-10",
    location: "Room 315",
    invoiceLink: "#",
  },
];

export const stationaryDetails = [
  {
    id: 0,
    item: "Textbook",
    brand: "Classmate",
    quantity: 450,
  },
  {
    id: 1,
    item: "Register",
    brand: "Oxford",
    quantity: 60,
  },
  {
    id: 2,
    item: "Log Book",
    brand: "Pioneer",
    quantity: 20,
  },
  {
    id: 3,
    item: "Marker & Pens",
    brand: "Fort",
    quantity: 360,
  },
];
